name: ValyrianCore
main: com.valyrian.core.main.MainClass
version: 1.0
softdepend: [HolographicDisplays]
authors: [Sulphate,AppleMC]
commands:
  lootchest:
    description: Modifies the LootChest.
  addkey:
    description: Adds a key to open the LootChest.
