name: ValyrianCore
main: com.valyrian.core.main.MainClass
version: 1.0
softdepend: [HolographicDisplays]
commands:
  lootchest:
    description: Modifies the LootChest.
  addkey:
    description: Adds a key/s to open the LootChest.
  addchest:
    description: Adds a chest.
